version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

references:
  general:
    image: &image circleci/node:12.16.1
  commands:
    npm_auth: &npm_auth
      name: NPM Auth
      command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    install_dependencies: &install_dependencies
      name: Install Dependencies
      command: npm i
  main_branch_filter: &main_branch_filter
    branches:
      only:
        - main

jobs:
  test:
    docker:
      - image: *image
    steps:
      - checkout
      - run: *npm_auth
      - run: *install_dependencies
      - run:
          name: Run Tests
          command: npm run test
  patch_release:
    docker:
      - image: *image
    steps:
      - checkout
      - run: *npm_auth
      - run: *install_dependencies
      - run:
          name: Release patch update
          command: npm version patch
  minor_release:
    docker:
      - image: *image
    steps:
      - checkout
      - run: *npm_auth
      - run: *install_dependencies
      - run:
          name: Release minor update
          command: npm version minor
  major_release:
    docker:
      - image: *image
    steps:
      - checkout
      - run: *npm_auth
      - run: *install_dependencies
      - run:
          name: Release major update
          command: npm version major

workflows:
  version: 2

  test:
    jobs:
      - test
  release:
    jobs:
      - patch_release:
          type: approval
          filters: *main_branch_filter
      - minor_release:
          type: approval
          filters: *main_branch_filter
      - major_release:
          type: approval
          filters: *main_branch_filter
